debug = false

logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[web]
  entryPoint = "traefik"
  dashboard = true
  address = ":8080"

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "MY_STAGE_DOMAIN"
watch = true
exposedByDefault = false

[acme]
email = "gilberto.souza@nyx.tc"
storage = "acme.json"
entryPoint = "https"
onDemand = false
onHostRule = true
[acme.httpChallenge]
entryPoint = "http"
